name: Test Simple Action

on:
  push:
    branches: [ main ]
    paths:
      - 'reports/**/*.html'

jobs:
  test-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Print hello message
      run: |
        echo "Hello from GitHub Actions!"
        echo "This is a test action that runs when HTML files are pushed"
        echo "Current time: $(date)"
        
    - name: List files
      run: |
        echo "Files in reports directory:"
        ls -la reports/
        
    - name: Show action info
      run: |
        echo "GitHub Actor: ${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"
        echo "Event: ${{ github.event_name }}"
        echo "Branch: ${{ github.ref_name }}"
